FROM ubuntu:18.04
RUN apt-get update && apt-get install -y \
    python3.6 \
    sqlite3 \
    python3-pip \
    && pip3 install Flask && pip3 install pysqlite3
COPY . /app
WORKDIR /app
EXPOSE 5000
ENV FLASK_APP "main.py"
ENV PYTHONPATH "${PYTHONPATH}:/app"
CMD "flask run"